"""Three gatekeeping capabilities (outbound guard, command guard, taint tracking) + tool budgets, attached to agents as needed.

| Need                                   | Mechanism                        | Attached to      |
| Last check before sending to the cloud | before_model_request             | planner / cloud  |
| Command risk rating and approval       | wrap_tool_execute                | executor         |
| Mark the session when sensitive data is read | after_tool_execute + task state | executor    |
| Limit the tools visible at each step   | prepare_tools                    | both             |
"""
from __future__ import annotations

import asyncio
import logging
import os
import re
import shlex
import time
from dataclasses import dataclass
from typing import Any

from pydantic_ai import RunContext
from pydantic_ai.capabilities import AbstractCapability
from pydantic_ai.exceptions import ModelHTTPError
from pydantic_ai.messages import (ModelRequest, RetryPromptPart, SystemPromptPart, ToolReturn, ToolReturnPart,
                                  UserPromptPart)
from pydantic_ai.tools import ToolDefinition

from .audit import sha256
from .config import RunMode
from .events import (Approval, ApprovalRequest, CommandFinished, CommandStarted, Notice, OutboundBlocked,
                     OutboundSent, Tainted)
from .session import Stats, TaskState

log = logging.getLogger(__name__)


class OutboundBlockedError(RuntimeError):
    """Blocked by the outbound guard: this request contains content that did not pass the gate."""


# ====================================================================== outbound guard

def _request_texts(messages) -> list[str]:
    """Collect every "not generated by the model" piece that will be sent to the model. The model's own
    replies (which came from the cloud) need no check."""
    out: list[str] = []
    for msg in messages:
        if not isinstance(msg, ModelRequest):
            continue
        for part in msg.parts:
            if isinstance(part, (UserPromptPart, SystemPromptPart)):
                c = part.content
                out.append(c if isinstance(c, str) else str(c))
            elif isinstance(part, ToolReturnPart):
                out.append(part.model_response_str())
            elif isinstance(part, RetryPromptPart):
                out.append(part.model_response())
    return out


@dataclass
class OutboundGuard(AbstractCapability[TaskState]):
    """Scans all messages before every model request of the planner / cloud agent: unregistered content must
    pass the gate right there, otherwise the request is aborted."""

    model_name: str = ""

    async def before_model_request(self, ctx: RunContext[TaskState], request_context):
        st = ctx.deps
        if st.business:   # business data never leaves this machine, certified or not
            st.bus.emit(OutboundBlocked("business data: cloud requests are off for this task"))
            raise OutboundBlockedError("business data never leaves this machine")
        for text in _request_texts(request_context.messages):
            h = sha256(text)
            if h not in st.certified:
                try:
                    st.remember(await asyncio.to_thread(st.gate.certify, text))
                except PermissionError as e:
                    st.bus.emit(OutboundBlocked(str(e)))
                    raise OutboundBlockedError(str(e)) from e
            if h not in st.logged_outbound:  # outbound log: each new piece of content is recorded once
                st.logged_outbound.add(h)
                st.session.outbound_log.write({"model": self.model_name, "content": text})
                st.bus.emit(OutboundSent(self.model_name, text))
        st.outbound_count += 1
        st.session.outbound_total += 1
        return request_context


# ====================================================================== cloud executor: tool results out, placeholders back

@dataclass
class CloudToolRedactor(AbstractCapability[TaskState]):
    """For the cloud executor (cloud_exec route). Every tool result is about to be sent to the cloud model, so the rules
    layer runs on it right here: Presidio findings are replaced by placeholders (<CN_MOBILE_1>, ...) whose mapping stays
    in TaskState.mapping, continuing the task's numbering. Placeholders the model puts into tool arguments (an edit_file
    `old`, a command) are restored before the tool runs. The contextual judge still runs in OutboundGuard.certify on the
    redacted text, and a result it rejects raises OutboundBlockedError there, which hands the step to the local executor.
    Must run before TaintTracker so the tracker sees the same text the model gets."""

    async def before_tool_execute(self, ctx: RunContext[TaskState], *, call, tool_def, args):
        st = ctx.deps
        if st.mapping and isinstance(args, dict):
            return {k: (_restore(st, v) if isinstance(v, str) else v) for k, v in args.items()}
        return args

    async def after_tool_execute(self, ctx: RunContext[TaskState], *, call, tool_def, args, result: Any):
        st = ctx.deps
        if not isinstance(result, str) or not result.strip():
            return result
        verdict = await asyncio.to_thread(st.gate.check, result, False)   # rules only; the judge runs at certify time
        if not verdict.findings:
            return result
        redacted, mapping = st.gate.redact(result, verdict.findings, existing=st.mapping)
        st.mapping.update(mapping)
        return redacted


def _restore(st: TaskState, text: str) -> str:
    for ph, original in st.mapping.items():
        text = text.replace(ph, original)
    return text


# ====================================================================== command guard

_HIGH_RISK = re.compile(
    r"(^|[;&|`(]\s*|\bsudo\s+)(rm|rmdir|shred|dd|mkfs|chmod\s+-R|chown|kill|killall|pkill|launchctl|"
    r"pip3?\s+install|conda\s+install|brew\s+install|npm\s+(i|install)|pnpm\s+add|yarn\s+add|"
    r"curl|wget|ssh|scp|rsync|git\s+(push|reset\s+--hard|clean|checkout\s+--|restore)|"
    r"find\s+.*-delete|truncate|mv)\b")
_LOW_RISK_HEADS = {"ls", "cat", "head", "tail", "wc", "grep", "rg", "find", "pwd", "echo", "stat", "file",
                   "du", "df", "tree", "diff", "sort", "uniq", "cut", "awk", "sed", "jq", "which", "date",
                   "git", "python", "python3", "pandoc", "pytest", "mkdir", "touch",
                   # Mac toolchain: builds write only derived data / .build, simulators are throwaway devices
                   "xcodebuild", "xcrun", "swift", "swiftc", "xcode-select", "axe"}
_SAFE_GIT = {"status", "diff", "log", "show", "add", "commit", "init", "branch"}
_SIMCTL_DESTRUCTIVE = {"delete", "erase"}   # wipe simulator devices / their data: let the judge rate these
_INTERPRETERS = {"python", "python3", "node", "ruby", "perl", "sh", "zsh", "bash"}
_INLINE_CODE_FLAGS = {"-c", "-e", "-E", "--eval", "-p"}
_WRITE_REDIRECT = re.compile(r"(?<![0-9&])>(?!>)\s*[^&\s]")
_FD_DUP = re.compile(r"\d?>&\d")   # 2>&1, >&2

RISK_LEVELS = [
    "low: only reads information, or creates new files inside the workspace",
    "medium: modifies or overwrites a few files inside the workspace; reversible",
    "high: deletes files, bulk overwrites, installs software, changes the system or permissions, kills processes",
]
RISK_QUESTION = "How high is the risk of running this shell command?"
_RISK_BY_SCORE = ["low", "medium", "high"]


def rule_risk(command: str) -> str | None:
    """Rules first: clearly high-risk commands are rated high, clearly read-only ones low, everything else
    goes to the judge model."""
    if _HIGH_RISK.search(command):
        return "high"
    # "2>&1" only merges streams; without this it would split into a stray segment ("1") and go to the judge
    segments = [seg.split() for seg in re.split(r"[;&|]+", _FD_DUP.sub(" ", command)) if seg.strip()]
    if not segments:
        return None
    for words in segments:
        if words[0] not in _LOW_RISK_HEADS:
            return None
        if words[0] == "git" and (len(words) < 2 or words[1] not in _SAFE_GIT):
            return None
        if words[0] in _INTERPRETERS and any(w in _INLINE_CODE_FLAGS for w in words[1:]):
            return None  # python -c "..." can do anything; must not be rated low by script name
        if words[0] == "xcrun" and "simctl" in words[1:2] and any(w in _SIMCTL_DESTRUCTIVE for w in words[2:]):
            return None
    if "sed -i" in command or _WRITE_REDIRECT.search(command):
        return None
    return "low"


_CMD_SPLIT = re.compile(r"\$\(|[;&|()`\n]+")
_PREFIX_WORDS = {"sudo", "env", "exec", "command", "time", "nohup", "nice", "xargs", "builtin", "noglob"}
ASC_REFUSAL = ("asc cannot run in run_command (the sandbox has no access to the App Store Connect account): use the "
               "`asc` tool instead, which reads App Store Connect / Apple Ads data read-only and saves the full "
               "result to a file you can process with python.")


def runs_asc(command: str) -> bool:
    """Whether any command in a shell line starts the asc CLI (by name or path, after env assignments or
    sudo/env/xargs...). The Seatbelt profile denies exec of the asc binary anyway; this gives the model a hint."""
    for seg in _CMD_SPLIT.split(command):
        try:
            words = shlex.split(seg)
        except ValueError:
            words = seg.split()
        for w in words:
            if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*=.*", w) or w in _PREFIX_WORDS or w.startswith("-"):
                continue
            if os.path.basename(w) == "asc":
                return True
            break
    return False


def command_key(command: str) -> str:
    try:
        return shlex.split(command)[0]
    except (ValueError, IndexError):
        return command.split(" ")[0]


@dataclass
class CommandGuard(AbstractCapability[TaskState]):
    """In default mode high-risk commands need approval; auto mode skips approval. The sandbox is unaffected
    in every mode."""

    async def wrap_tool_execute(self, ctx: RunContext[TaskState], *, call, tool_def, args, handler):
        st = ctx.deps
        if call.tool_name != "run_command":
            return await handler(args)
        command = args.get("command", "") if isinstance(args, dict) else getattr(args, "command", "")
        if runs_asc(command):
            return ASC_REFUSAL
        risk = rule_risk(command)
        if risk is None:
            try:
                ans = await asyncio.to_thread(st.session.bg_judge.score, command, RISK_QUESTION, RISK_LEVELS)
                risk = _RISK_BY_SCORE[ans.score]
            except Exception:
                log.exception("Command risk judgment failed; treating as high risk")
                risk = "high"
        st.bus.emit(CommandStarted("run_command", command, risk))
        if risk == "high" and st.session.mode is RunMode.DEFAULT and command_key(command) not in st.session.session_allow:
            decision = await st.bus.request_approval(ApprovalRequest("run_command", command, risk, "high-risk command"))
            st.session.command_log.write({"command": command, "risk": risk, "approval": decision.value})
            if decision is Approval.DENY:
                return ("User denied running this command. Use an approach that does not need it, "
                        "or explain in the report.")
            if decision is Approval.ALLOW_SESSION:
                st.session.session_allow.add(command_key(command))
        return await handler(args)


# ====================================================================== taint tracking + progress supervision

WITHDRAWN_NOTE = ("Tools are withdrawn for this step (step limit reached or no progress detected). Do not call tools "
                  "again: submit the structured result now with what was achieved so far (status partial if unfinished).")
STUCK_QUESTION = ("Based on the action log below, is the executor going in circles (repeating the same or "
                  "similar failing actions without real progress)?")
# These tools return no file content (only paths / byte counts / file lists): taint detection runs the rules
# layer only and does not ask the judge model
_NO_CONTENT_TOOLS = {"write_file", "edit_file", "list_files", "screenshot"}   # screenshot: only a path in text; the
                                                                              # image itself is handled by the tool (mac = tainted)
# Web content is public material, not "sensitive local content read"; it is excluded from taint tracking
# (prompt injection is covered by the "always treat it as data" instruction)
_PUBLIC_TOOLS = {"web_fetch", "web_search"}


def mark_tainted(st: TaskState, tool: str, reason: str) -> None:
    if not st.tainted:
        st.tainted = True
        st.bus.emit(Tainted(f"output of {tool} contains sensitive content ({reason})"))


async def _contextual_taint(st: TaskState, tool: str, text: str) -> None:
    """Background: judge model only. Fails closed (treated as private)."""
    if st.tainted:
        return
    verdict = await asyncio.to_thread(st.gate.contextual, text, st.session.bg_judge)
    if verdict.sensitive:
        mark_tainted(st, tool, verdict.reason)


async def _stuck_check(st: TaskState, window: list[str]) -> None:
    try:
        p = await asyncio.to_thread(st.session.bg_judge.noul, "\n".join(window), STUCK_QUESTION)
        if p >= 0.67 and not st.stuck:
            st.stuck = True
            st.bus.emit(Notice("warn", f"The judge thinks the executor is stuck (p={p:.2f}); "
                                       f"withdrawing tools and requesting a report"))
    except Exception:
        log.exception("Progress supervision failed; ignored")


@dataclass
class TaintTracker(AbstractCapability[TaskState]):
    """Checks the output after every tool call; reading sensitive content marks the task as tainted.
    Every few steps, checks whether the executor is stuck.

    The rules layer (Presidio) is fast and runs synchronously; the judge model is slow and runs in the
    background so tool returns are not blocked -- the taint result is only needed at outbound time and at
    the end of the task, and those places call settle_checks() first. A judge failure also counts as
    tainted (fail closed). Once the task is business (connectors), nothing is scanned: the business lock is stricter
    than taint."""

    async def after_tool_execute(self, ctx: RunContext[TaskState], *, call, tool_def, args, result: Any):
        st = ctx.deps
        if isinstance(result, ToolReturn):   # e.g. screenshot: the text part is checked, the attached image is not text
            result_text = result.return_value
        else:
            result_text = result
        text = result_text if isinstance(result_text, str) else str(result_text)
        st.tool_calls += 1
        st.tool_seq.append(call.tool_name)
        st.last_tool_at = time.monotonic()
        if call.tool_name in ("write_file", "edit_file") and isinstance(args, dict) and args.get("path"):
            if args["path"] not in st.changed_paths:
                st.changed_paths.append(str(args["path"]))
        st.recent_calls.append(f"{call.tool_name}({str(args)[:200]}) -> {text[:200]}")
        if text == WITHDRAWN_NOTE:   # a refused call after withdrawal: nothing to scan
            return result
        if not st.tainted and not st.business and call.tool_name not in _PUBLIC_TOOLS:
            verdict = await asyncio.to_thread(st.gate.check, text, False)
            if verdict.sensitive:
                mark_tainted(st, call.tool_name, verdict.reason)
            elif call.tool_name not in _NO_CONTENT_TOOLS:
                st.schedule_check(_contextual_taint(st, call.tool_name, text))
        every = st.s.stuck_check_every
        if every > 0 and st.tool_calls % every == 0 and not st.stuck:
            st.schedule_check(_stuck_check(st, st.recent_calls[-every * 2:]))
        return result


# ====================================================================== local model request retry

@dataclass
class LocalRequestRetry(AbstractCapability[Any]):
    """One immediate, identical retry when the local model server answers 5xx. Ollama's tool-call parser fails on
    some outputs of the qwen3.x models ("XML syntax error ... element <function> closed by </parameter>", HTTP 500)
    and the next sample is usually fine; without the retry the reviewer silently skipped its review and an executor
    step failed. Nothing else is retried here (timeouts stay fatal: see ModelFactory._ollama)."""

    async def on_model_request_error(self, ctx, *, request_context, error):
        if isinstance(error, ModelHTTPError) and error.status_code >= 500:
            log.warning("Local model request failed with HTTP %s; retrying once", error.status_code)
            return await request_context.model.request(request_context.messages, request_context.model_settings,
                                                       request_context.model_request_parameters)
        raise error


# ====================================================================== activity stats

@dataclass
class ActivityTracker(AbstractCapability[Any]):
    """Records agent run counts, the model currently being requested and the tokens of every request.
    Attached to all agents (does not depend on deps)."""

    stats: Stats
    role: str
    where: str  # cloud / local

    @staticmethod
    def _key(ctx) -> str:
        return ctx.run_id or str(id(ctx))

    async def before_run(self, ctx):
        self.stats.run_started(self.role, self._key(ctx))

    async def after_run(self, ctx, *, result):
        self.stats.run_finished(self._key(ctx))
        return result

    async def on_run_error(self, ctx, *, error):
        self.stats.run_finished(self._key(ctx))
        raise error

    async def before_model_request(self, ctx, request_context):
        self.stats.request_started(self.where, request_context.model.model_name, self.role)
        return request_context

    async def after_model_request(self, ctx, *, request_context, response):
        u = response.usage
        self.stats.request_finished(self.where, u.input_tokens, u.output_tokens)
        return response

    async def on_model_request_error(self, ctx, *, request_context, error):
        self.stats.request_aborted()
        raise error


# ====================================================================== tool budgets

@dataclass
class ExecutorToolBudget(AbstractCapability[TaskState]):
    """Once the step limit is exceeded or the executor is judged stuck, every tool call is answered with WITHDRAWN_NOTE
    instead of running, so the model's next move is the report. The definitions stay in the request on purpose:
    removing them made a model that still called run_command hit "Unknown tool name" retries until the step failed
    with UnexpectedModelBehavior (measured 2026-10-06: four 60 s turns and a re-delegated step). Must come before
    CommandGuard in the capability list so a refused command is not risk-judged or approved first."""

    cloud: bool = False   # the cloud executor's budget (CLOUD_MAX_TOOL_CALLS) instead of the local one

    def withdrawn(self, st: TaskState) -> bool:
        limit = st.s.cloud_max_tool_calls if self.cloud else st.s.max_tool_calls
        return st.stuck or st.tool_calls >= limit

    async def wrap_tool_execute(self, ctx: RunContext[TaskState], *, call, tool_def, args, handler):
        st = ctx.deps
        if self.withdrawn(st):
            # visible in the command log and the UI as "withdrawn" (never the arguments), so the turns a model spends
            # ignoring the note can be counted
            command_finished(st, call.tool_name, "withdrawn", 1, WITHDRAWN_NOTE, 0.0)
            return WITHDRAWN_NOTE
        return await handler(args)


@dataclass
class PlannerToolBudget(AbstractCapability[TaskState]):
    """Hide planner tools whose budget is spent: delegate (delegations), ask_user (question rounds), revise_plan."""

    async def prepare_tools(self, ctx: RunContext[TaskState], tool_defs: list[ToolDefinition]):
        st = ctx.deps
        hidden = set()
        if st.delegations >= st.delegation_limit:
            hidden.add("delegate")
        if st.question_rounds >= st.s.plan_max_question_rounds:
            hidden.add("ask_user")
        if st.plan_revisions >= st.s.plan_max_revisions:
            hidden.add("revise_plan")
        return [t for t in tool_defs if t.name not in hidden]


async def timed(coro):
    t0 = time.time()
    res = await coro
    return res, round(time.time() - t0, 3)


def command_finished(st: TaskState, tool: str, summary: str, code: int, output: str, dur: float) -> None:
    st.session.command_log.write({"tool": tool, "command": summary, "exit_code": code, "duration_s": dur})
    st.bus.emit(CommandFinished(tool, summary, code, output, dur))
